global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'video-enhancer'
    static_configs:
      - targets: ['localhost:8000']  # Your local API endpoint
    metrics_path: /metrics
    scrape_interval: 5s  # More frequent scraping for this target
