global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'video-enhancer'
    static_configs:
      - targets: ['localhost:8000']  # Your local API endpoint
    metrics_path: /metrics
    scrape_interval: 5s  # More frequent scraping for this target


# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "
